### ISSUE TITLE
AttributeError: 'JSONDecodeError' object has no attribute 'reason'

### ISSUE THREAD

**Issue by coagulant** [facconi/sentry-redmine#2]
If user doesn't have sufficient permisssions to add issue, plugin errors into 500 page.

```
Internal Server Error: /group/676/actions/redmine/
Traceback (most recent call last):
  File "/home/sentry/envs/sentry/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = callback(request, *callback_args, **callback_kwargs)
  File "/home/sentry/envs/sentry/lib/python2.7/site-packages/sentry/web/decorators.py", line 146, in wrapped
    return func(request, *args, **kwargs)
  File "/home/sentry/envs/sentry/lib/python2.7/site-packages/sentry/web/decorators.py", line 106, in _wrapped
    return func(request, *args, **kwargs)
  File "/home/sentry/envs/sentry/lib/python2.7/site-packages/sentry/web/frontend/groups.py", line 449, in group_plugin_action
    response = plugin.get_view_response(request, group)
  File "/home/sentry/envs/sentry/lib/python2.7/site-packages/sentry/plugins/base.py", line 321, in get_view_response
    response = self.view(request, group)
  File "/home/sentry/envs/sentry/lib/python2.7/site-packages/sentry/plugins/bases/issue.py", line 166, in view
    request=request,
  File "/home/sentry/envs/sentry/lib/python2.7/site-packages/sentry_redmine/plugin.py", line 120, in create_issue
    raise forms.ValidationError('Unable to reach Redmine host: %s' % (e.reason,))
AttributeError: 'JSONDecodeError' object has no attribute 'reason'
```

**Comment by aadis** [comment]
Hi, I've forked the repository from upstream. You should prolly log the issue there :)

**Comment by coagulant** [comment]
What is upstream repo location?

**Comment by aadis** [comment]
sentry-redmine was part of the sentry codebase till it was removed. I packaged it from the sentry history files.

I guess this is as good a place to manage sentry-redmine. So lets go ahead :)
